fix(head): fix Dropout inplace operation make gradient computation failed
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace
operation: [torch.cuda.HalfTensor [128, 1280, 1, 1]], which is output 0 of ReluBackward1, is at
version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that
failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).